config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get '/about' => 'users#about'
	delete '/logout' => 'sessions#destroy'
  get '/posts/search' => 'posts#search'
  resources :messages, only: [:new, :create]
  resources :posts, only: [:new, :create, :update, :edit, :index, :show, :destroy] do
    resources :requests, only: [:new, :create, :destroy, :show]
  end
  resources :users, only: [:new, :create, :edit, :update, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  # (validates: inserts into record only if there is an email)
  # (uniqueness: checks for existing email
  has_many :posts
  has_many :requests

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # def index
  #   @messages = Message.all
  # end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
      flash[:newUser] = "Message was sent successfully"
    else
      render "/messages/new"
      flash[:notice] = "Error occured, message was not sent"
    end
  end

  private
    def message_params
      params.require(:message).permit(:name, :phone, :subject, :message)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.shuffle
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.assign_attributes(:user_id => session[:user_id])
    # @city = :city
    @post.assign_attributes(:map_url => "https://maps.googleapis.com/maps/api/staticmap?center=#{@post.city}&zoom=11&size=300x200")
    if @post.save
      flash[:newUser] = "Post: #{@post.title} successfully created"
      redirect_to "/posts/#{@post.id}"
    else
      render "/posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      @post.update(:map_url => "https://maps.googleapis.com/maps/api/staticmap?center=#{@post.city}&zoom=11&size=300x200")
      flash[:newUser] = "Post: #{@post.title} successfully updated"
      redirect_to "/posts/#{@post.id}"
    else
      flash[:notice] = "Post: #{@post.title} was not successfully updated. Missing parameters."
      redirect_to "/posts/#{@post.id}"
    end
  end

  def show
    @post = Post.find(params[:id])
  end


  def destroy
    @post = Post.find(params[:id])
    @post.requests.all.each {|r| r.destroy}
    if @post.destroy
      flash[:newUser] = "Post: #{@post.title} successfully deleted"
      redirect_to "/posts"
    end
  end

  def search
    @query = params[:query]
    @posts = Post.all
    @match = []

    @posts.each do |p|
      array = []
      p.title.split(/[\s,]+/).each {|w| array.push(w.downcase)}
      p.body.split(/[\s,]+/).each {|w| array.push(w.downcase)}
      p.city.split(/[\s,]+/).each {|w| array.push(w.downcase)}
      p.user.first_name.split(/[\s,]+/).each {|w| array.push(w.downcase)}
      @query.split(/[\s,]+/).each do |m|
        @match.push(p.id) if array.include?(m.downcase)
      end
    end

    @match.uniq!

  end

  private
    def post_params
      params.require(:post).permit(:title, :rate, :city, :profile_url, :body)
    end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    @request = Request.new
    @post = params[:post_id]
  end

  def create
    @request = Request.new(req_params)
    @request.update(post_id: params[:post_id], user_id: session[:user_id])
    if session[:user_id]
      if @request.save
        redirect_to "/users/#{session[:user_id]}"
        flash[:newUser] = "Request for: #{@request.post.title} successfully submitted"
      else
        render "/posts/<%=params[:post_id]%>/requests/new"
        flash[:notice] = "Error. Request was not submitted"
      end
    else
      flash[:notice] = "You must be logged in to submit a request."
      redirect_to "/posts/#{params[:post_id]}"
    end
  end

  def destroy
    @request = Request.find(params[:id])
    if @request.destroy
      redirect_to user_path
    end
  end

  def show
    @request = Request.find(params[:id])
  end

private
  def req_params
    params.require(:request).permit(:message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(email: user_params[:email]).first
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      flash[:loggedIn] = "Successfully logged in. Greetings, #{@user.first_name}!"
      redirect_to "/"
    else
      flash[:notice] = "Oops! There was an issue with your log in credentials."
      redirect_to "/sessions/new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:newUser] = %Q[Thank you for signing up, please <a href="/sessions/new" class='logLink'>log in</a> to continue]
      redirect_to "/"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:newUser] = "Account information successfully updated."
      redirect_to "/users/#{params[:id]}"
    else
      flash[:notice] = "There was an issue, account information was not updated."
      redirect_to "/users/#{params[:id]}/edit"
    end
  end

  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to new_session_path
      flash[:notice] = "Please log in to proceed."
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="style.css"> -->
  <link href='https://fonts.googleapis.com/css?family=Mr+Bedfort' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Arimo:400,700' rel='stylesheet' type='text/css'>
  <title>TeachMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <% flash.each do |name, msg| %>
    <% if name == "newUser" %>
    <%= content_tag :div, sanitize(msg), class: name %>
    <% else %>
    <%= content_tag :div, msg, class: name %>
    <% end %>
  <% end %>

  <ul class='header'>
    <li class='header'><a href="/">Main</a></li>
    <li class='header'><a href="/about">About</a></li>
    <li class='header'><a href="/messages/new">Contact</a></li>
    <% if current_user %>
      <li class='header'><a href="/users/<%=session[:user_id]%>">Dashboard</a></li>
      <li class='header'><a href="/users/<%=session[:user_id]%>/edit">My Account</a></li>
      <li class='header'><a href="/logout" data-method="delete" rel="nofollow">Log out</a></li>
    <% else %>
      <li class='header'><a href="/sessions/new">Log In</a></li>
      <li class='header'><a href="/users/new">Sign Up</a></li>
    <% end %>
  </ul>

<%= yield %>

<%=render("shared/footer") %>
</body>
</html>

app/views/messages/new.html.erb
<h1 class='title'><span class='regularFont'>Contact </span>Teach<span class='logoM'>M</span>e:</h1>

<div class="container">

  <div class="container message contact">
  <h3 class="contactHeader">Contact Form</h3>
      <%= form_for @message do |f| %>
      <div class='messageLine contact first'>
        <p class='messageDetail contact'>Name: </p>
        <%= f.text_field :name, :required => true, :class => 'messageField contact'%>
      </div>

      <div class='messageLine contact'>
        <p class='messageDetail contact'>Phone: </p>
        <%= f.text_field :phone, :required => true, :class => 'messageField contact'%>
      </div>

      <div class='messageLine contact'>
      <p class='messageDetail contact'>Email: </p>
      <%= f.text_field :email, :required => true, :class => 'messageField contact'%>
      </div>

      <div class='messageLine contact'>
        <p class='messageDetail contact'>Subject: </p>
        <%= f.text_field :subject, :required => true, :class => 'messageField contact'%>
      </div>

      <div class='messageLine contact'>
        <p class='messageDetail contact'>Message: </p>
        <%= f.text_area :message, :required => true, :class => 'messageBody contact' %>
      </div>

      <div class='messageLine contact'>
        <p class='messageDetail contact'>
          <%= image_submit_tag("submit.png", :alt => "submit form", :class => 'submitButton') %>
      </div>

  <% end %>

  </div>

  <div class="container message contact">


  <h3 class="contactHeader">Address & Contact Information</h3>
  <h4 class="contactInfo">1520 2nd St <br>
      Santa Monica, CA 90401<br>
      United States</h4>

  <h4 class="contactInfo"> addyproject1@gmail.com</h4>
  <h4 class="contactInfo"> (877) 348-5665 </h4>

  <img src="https://maps.googleapis.com/maps/api/staticmap?center=1520%202ndStreet%20SantaMonica,%20CA&zoom=14&size=400x300" alt="image of General Assembly in Santa Monica" class="aboutMap"/>
  </div>

</div>

app/views/posts/edit.html.erb
<div class="container message">

<h1 class='title'><span class='regularFont'>Edit your <%=@post.title%> Post @  </span>Teach<span class='logoM'>M</span>e!</h1>

<%= form_for @post do |f| %>

<div class='messageLine signup first'>
  <p class='messageDetail signup'>Title: </p>
  <%= f.text_field :title, :class => 'messageField'%>
</div>

<div class='messageLine signup'>
  <p class='messageDetail signup'>Rate: </p>
  <%= f.text_field :rate, :class => 'messageField signup'%>
</div>

<div class='messageLine signup'>
  <p class='messageDetail signup'>City: </p>
  <%= f.text_field :city, :class => 'messageField signup'%>
</div>

<div class='messageLine signup'><p class='messageDetail signup' style="font-size:20px;">Profile URL: </p><%= f.text_field :profile_url, :class => 'messageField signup'%>
</div>



<div class='messageLine signup'>
  <p class='messageDetail signup'>Description: </p>
  <%= f.text_area :body, :class => 'messageBody signup'%>
</div>

<div class='messageLine newPost' style="margin-bottom:30px;">
  <%= f.submit "Save", :style => "width: 100px; height: 30px; background-color: green; display: inline-block; vertical-align: top; border-radius: 5px; position: relative; left: 100px; line-height:20px; font-size:15px; color:white;" %>

  <a href="/posts/<%=@post.id%>" data-method="delete" rel="nofollow" style = "width: 100px; height: 30px; background-color: red; display: inline-block; vertical-align: top; border-radius: 5px; position: relative; left: 100px; line-height:30px; font-size:15px; color:white;">Delete Post</a>

</div>



<% end %>

</div>

app/views/posts/index.html.erb
<div id="coverPic">
  <p class="bfQuote">
    "Tell me and I forget.</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Teach me and I remember."</br>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span id="bfSign"> Benjamin Franklin </span>
  </p>
</div>

<h1 class='title' style="display:inline-block; width: 130px;">Teach<span class='logoM'>M</span>e:</h1>

<div style="display:inline-block; width:230px; height:20px; vertical-align:top; margin-top: 14px">
    <%= form_tag("/posts/search", method: "get") do %>
      <%= text_field_tag :query,nil, :placeholder => "subject or location", :style => "height:27px; width: 150px; text-align:center; font-size:13px;" %>
      <%= image_submit_tag("Search.png", :name => 'filter', :style => "width:28px; vertical-align: top;") %>

    <% end %>

</div>

<div class ='container'>

  <% @posts.each do |p|%>
    <a href="/posts/<%= p.id %>">
    <div class="indexListing">
      <div class="indexImage" style="background-image: url('<%= p.profile_url %>'); background-size: cover; background-repeat: no-repeat;">

      </div>
    <h6><%=p.title.capitalize%></h6>
    <p>With tutor: <%= p.user.first_name%></p>
  </div>
    </a>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="container message">

<h1 class='title'><span class='regularFont'>Create New Post @ </span>Teach<span class='logoM'>M</span>e!</h1>

<%= form_for @post do |f| %>

<div class='messageLine signup first'>
  <p class='messageDetail signup'>Title: </p>
  <%= f.text_field :title, :required => true, :class => 'messageField'%>
</div>

<div class='messageLine signup'>
  <p class='messageDetail signup'>Rate: </p>
  <%= f.text_field :rate, :required => true, :class => 'messageField signup'%>
</div>

<div class='messageLine signup'>
  <p class='messageDetail signup'>City: </p>
  <%= f.text_field :city, :required => true, :class => 'messageField signup'%>
</div>

<div class='messageLine signup'>
  <p class='messageDetail signup' style="font-size:20px;">Profile URL: </p>
  <%= f.text_field :profile_url, :required => true, :class => 'messageField signup'%>
</div>



<div class='messageLine signup'><p class='messageDetail signup'>Description: </p><%= f.text_area :body, :required => true, :class => 'messageBody signup'%></div>
<div class='messageLine newPost'><%= f.submit "Create Post", :class => "signButton new" %></div>

<% end %>

</div>

app/views/posts/search.html.erb
<div id="coverPic">
  <p class="bfQuote">
    "Tell me and I forget.</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Teach me and I remember."</br>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <span id="bfSign"> Benjamin Franklin </span>
  </p>
</div>

<h1 class='title' style="display:inline-block; width: 130px;">Teach<span class='logoM'>M</span>e:</h1>

<div style="display:inline-block; width:230px; height:20px; vertical-align:top; margin-top: 14px">
    <%= form_tag("/posts/search", method: "get") do %>
      <%= text_field_tag :query,nil, :placeholder => "enter subject / location", :style => "height:27px; width: 150px; text-align:center;" %>
      <%= image_submit_tag("Search.png", :name => 'filter', :style => "width:28px; vertical-align: top;") %>
    <% end %>
</div>

<p style="font-weight:bold; font-size:22px; margin-top:30px;">Search Results for "<%= @query %>":</p>

<div class ='container'>
  <% unless @match.any? %>
    <p style="margin: 20px auto; min-height:80px;"> No listings match the search parameters</p>
  <% end %>

  <% @match.each do |p|%>
    <a href="/posts/<%= p %>">
    <div class="indexListing">
        <div class="indexImage" style="background-image: url('<%= Post.find(p).profile_url %>'); background-size: cover; background-repeat: no-repeat;">

        </div>
        <h6> <%=Post.find(p).title.capitalize%> </h6>
        <p> With tutor: <%= Post.find(p).user.first_name%> </p>
    </div>
    </a>
  <% end %>

</div>

app/views/posts/show.html.erb
<h1 class='title'>Teach<span class='logoM'>M</span>e:</h1>

<div class="container" style="padding-top: 30px;">

<!-- <h1 class='about'>"Patience, all your questions will be answered.."</h1> -->
    <div class="postLeft" style="text-align: left; width: 400px; display:inline-block; vertical-align:top; margin-right: 40px;">

      <h2 class='postTitle' style="font-size:35px; font-weight:bold; padding-bottom:15px; position: relative;"> <%= @post.title.capitalize %> </h2>

      <p class='poster' style="font-size:20px; padding-bottom:15px;">
        Instructor: <%= @post.user.first_name %>
      </p>

      <p class='postRate' style="font-size:20px; padding-bottom:15px;">
        Rate: <%= @post.rate %>
      </p>

      <p class='postCity' style="font-size:20px; padding-bottom:15px;">
        Location: <%= @post.city.capitalize %>
      </p>

      <p class='postBody' style="font-size:18px; padding-bottom:15px;">
        <%= @post.body %>
      </p>


        <a href="/posts/<%=@post.id%>/requests/new">
          <button type="button" name="report" style="width:110px; height: 35px; font-size: 17px; border-radius: 5px; line-height:28px; margin: 35px 5px; background-color:green; color:white; vertical-align:top; border:none">Request
          </button>
        </a>

      <% if session[:user_id] == @post.user.id %>
        <a href="/posts/<%= @post.id%>/edit">
          <button type="button" name="report" style="width:110px; height: 35px; font-size: 17px; border-radius: 5px; line-height:28px; margin: 35px 5px; background-color:blue; color:white; vertical-align:top; border:none">Edit
          </button>
        </a>

      <% end %>

    </div>

    <div class="postRight" style="display:inline-block;">
      <div class='postProfile'> <%= image_tag @post.profile_url, alt: "profile picture",style: "width:300px; height: 200px; margin: 15px auto;" %>
      </div>

      <a href="https://www.google.com/maps/place/<%= @post.city %>">
        <div class='postGoogle'><%= image_tag @post.map_url, alt: "map picture",style: "width:300px; height: 200px; margin: 15px auto;" %>
        </div>
      </a>
    </div>



</div>

app/views/requests/new.html.erb
<div class="container message">

<h1 class='title'><span class='regularFont'>Create Request @</span>Teach<span class='logoM'>M</span>e!</h1>

<p style="margin-top:30px; font-weight:bold; font-size:20px;">Your inquery for <%=Post.find(params[:post_id]).title%> lessons</p>

<%= form_for @request, url: post_requests_path do |f| %>
  <div class='messageLine signup'>
      <p class='messageDetail signup' style="margin-right:0; margin-top:30px;">Message:</p>
      <%= f.text_area :message, :required => true, :class => 'messageBody', :style => "margin-top:30px; font-size:20px;" %>
  </div>

<%= f.submit "Send Request", :class => "signButton", :style => "width:150px; position:relative; top:160px;" %>

<% end %>

</div>

app/views/requests/show.html.erb
<h1 class='title'><span class='regularFont'>Tutor Request @</span>Teach<span class='logoM'>M</span>e!</h1>


<div class="dashLeft" style="width:600px;min-height:400px;border:1px solid grey; margin:10px auto; display: inline-block; vertical-align: top;">

  <p style="font-size: 21px; font-weight:bold; position:relative; margin: 10px 5%;"> Request to book <%= @request.post.title%> lesson from <%= @request.user.first_name%></p>
<hr style="margin-left:3%; width: 93%">
    <div class="messageBox" style="text-align: left;">

    <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%; margin-top:25px;"> <span style="font-weight:bold;">To:</span> <%= @request.post.user.first_name%> <%= @request.post.user.last_name%></p>

    <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%;"> <span style="font-weight:bold;">From:</span> <%= @request.user.first_name%> <%= @request.user.last_name%></p>

    <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%;"> <span style="font-weight:bold;">Email:</span> <%= @request.user.email %></p>

    <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%;"> <span style="font-weight:bold;">Subject:</span>  Your tutoring lesson: <%= @request.post.title.capitalize %>  in <%= @request.post.city %></p>

    <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%;"> <span style="font-weight:bold;">Message:</span> <p style="font-size: 17px; font-weight:normal; position:relative; margin: 15px 7%;"> Hi, <br>
    <%= @request.message %> </p>
    </p>
    </div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
<p id='footer1'>TeachMe<a href="#top" class='returnTop'>Return to Top &uarr;</a></p>
<hr>
<ul class='foot About'>
  <li class='footerLine first'>About</li>
  <li class='footerLine' >|&nbsp;&nbsp;&nbsp;&nbsp;Our Company</li>
  <li class='footerLine'>Terms & Conditions</li>
</ul>

<ul class='foot Contact'>
  <li class='footerLine first'>Contact</li>
  <li class='footerLine'>|&nbsp;&nbsp;&nbsp;&nbsp;Customer Service </li>
  <li class='footerLine'>Press</li>
</ul>

<ul class='foot Connect'>
  <li class='footerLine first'>Connect</li>
  <li class='footerLine'>|&nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag "fb.jpg", alt: "facebook link" %> &nbsp;Facebook</li>
  <li class='footerLine'>
    <%= image_tag "twit.jpg", alt: "twitter link" %> &nbsp;Twitter
  </li>

  <li class='footerLine'>
    <%= image_tag "goog.jpg", alt: "google link" %> &nbsp;Google
  </li>

  <li class='footerLine'>
    <%= image_tag "pint.jpg", alt: "pinterest link" %> &nbsp;Pinterest
  </li>

</ul>

</div>

app/views/users/about.html.erb
<div class="container">

<h1 class='title'>Teach<span class='logoM'>M</span>e</h1>

<h1 class='about'>"Patience, all your questions will be answered.."</h1>

<h3 class='about'>Who are we?</h3>
<p class='about'>
We're a small company in Santa Monica that specializes in bringing people together to share their knowledge and skills with one another. Learning is fun, right? We agree, we beleive learning can be even better when it's one on one, and at the exact pace the indivdual needs. Browse our listings, and don't be shy to post what you can teach someone today!
</p>

<h3 class='about'>Who are the teachers?</h3>
<p class='about'>
They're aliens that decided to step away from the entertainment industry after wrapping up the movie "Independence Day." Just kidding, of course. They're people just like you and me! Everyone is good (or great) at something, and are teachers have decided to pass their knowledge on to you! Sometimes for money, and sometimes they're willing to do exchange lessons for lessons. What are you bringing to the table? Feel free to post your offering and contact other "teachers" that interest you.
</p>


<h3 class='about'>Who can sign up?</h3>
<p class='about'>
Only people with the first name "Neo." Kidding again. Anyone can sign up, we encourage more users, but trust that people offering lessons are indeed qualified to be teaching. Be honest, have integrity, and test yourself. Are you genuinly capable of teaching others? We believe in you!!
</p>

<h3 class='about'>How do I get connected?</h3>
<p class='about'>
Open an account at with the "Sign Up" link at the top of each page, and wait for interested parties to inquire. Connect and share on your favorite social media pages to get spread the word and breed more users!
</p>

<h3 class='about'>Can I feature you in our press media?</h3>
<p class='about'>
Awesomness! Please use our "Press" link in the "Contact" section in the footer or use our "Contact Us" form to set something up. We look forward to hearing from you!
</p>

</div>

app/views/users/edit.html.erb
<div class="container">

<h1 class='title'><span class='regularFont'>Edit Profile @</span>Teach<span class='logoM'>M</span>e!</h1>

<%= form_for @user do |f| %>

      <div class='messageLine signup first'>
        <p class='messageDetail signup'>First Name: </p>
        <%= f.text_field :first_name, :required => true, :class => 'messageField'%>
      </div>

      <div class='messageLine signup'>
        <p class='messageDetail signup'>Last Name: </p>
        <%= f.text_field :last_name, :required => true, :class => 'messageField signup'%>
      </div>

      <div class='messageLine signup'>
        <p class='messageDetail signup'>Email: </p>
        <%= f.text_field :email, :required => true, :class => 'messageField signup'%>
      </div>

      <div class='messageLine signup'>
        <%= f.submit "Update", :class => "signButton new" %>
      </div>

<% end %>

</div>

app/views/users/new.html.erb
<div class="container message">

<h1 class='title'><span class='regularFont'>Sign up with </span>Teach<span class='logoM'>M</span>e!</h1>

<%= form_for @user do |f| %>

      <div class='messageLine signup first'>
        <p class='messageDetail signup'>First Name: </p>
        <%= f.text_field :first_name, :required => true, :class => 'messageField'%>
      </div>

      <div class='messageLine signup'>
        <p class='messageDetail signup'>Last Name: </p>
        <%= f.text_field :last_name, :required => true, :class => 'messageField signup'%>
      </div>

      <div class='messageLine signup'>
        <p class='messageDetail signup'>Email: </p>
        <%= f.text_field :email, :required => true, :class => 'messageField signup'%>
      </div>

      <div class='messageLine signup'><p class='messageDetail signup'>Password: </p>
        <%= f.password_field :password, :required => true, :class => 'messageField signup'%>
      </div>

      <div class='messageLine signup'>
        <%= f.submit "Create Account", :class => "signButton new" %>
      </div>

<% end %>

</div>